Repository impress-org/givewp, pull requests merged in 2020-07, with the labels that each got.

#4917 Onboarding wizard is now scaffolded
  assets/src/js/admin/onboarding-wizard/app/index.js
  assets/src/js/admin/onboarding-wizard/app/style.scss
  assets/src/js/admin/onboarding-wizard/index.js
  includes/admin/class-give-welcome.php
  includes/admin/settings/class-settings-advanced.php
  includes/install.php
  readme.txt
  src/Views/Admin.php
  src/Views/Admin/Pages/OnboardingWizard.php
  src/Views/Admin/Pages/templates/onboarding-wizard-template.php
  webpack.config.js
Labels: needs: copy, needs: web doc

#4896 fix: renewal donations are now factored into Reports
  src/API/Endpoints/Reports/AverageDonation.php
  src/API/Endpoints/Reports/Endpoint.php
  src/API/Endpoints/Reports/Income.php
  src/API/Endpoints/Reports/IncomeBreakdown.php
  src/API/Endpoints/Reports/TotalDonors.php
  src/API/Endpoints/Reports/TotalIncome.php
  src/API/Endpoints/Reports/TotalRefunds.php
Labels: needs: testing

#4926 fix: prevent decimal issues when using ',' as decimal separator
  src/API/Endpoints/Reports/AverageDonation.php
  src/API/Endpoints/Reports/FormPerformance.php
  src/API/Endpoints/Reports/Income.php
  src/API/Endpoints/Reports/IncomeBreakdown.php
  src/API/Endpoints/Reports/PaymentMethods.php
  src/API/Endpoints/Reports/TopDonors.php
  src/API/Endpoints/Reports/TotalIncome.php
Labels: needs: testing

#4925 Update Give Bootstrapping with Service Container and Service Providers
  give.php
  src/API/API.php
  src/API/Endpoints/Reports/AverageDonation.php
  src/API/Endpoints/Reports/DonationsVsIncome.php
  src/API/Endpoints/Reports/Endpoint.php
  src/API/Endpoints/Reports/FormPerformance.php
  src/API/Endpoints/Reports/Income.php
  src/API/Endpoints/Reports/IncomeBreakdown.php
  src/API/Endpoints/Reports/PaymentMethods.php
  src/API/Endpoints/Reports/PaymentStatuses.php
  src/API/Endpoints/Reports/RecentDonations.php
  src/API/Endpoints/Reports/TopDonors.php
  src/API/Endpoints/Reports/TotalDonors.php
  src/API/Endpoints/Reports/TotalIncome.php
  src/API/Endpoints/Reports/TotalRefunds.php
  src/API/RestRoute.php
  src/Container/Container.php
  src/Container/Exceptions/BindingResolutionException.php
  src/ServiceProviders/LegacyServiceProvider.php
  src/ServiceProviders/RestAPI.php
  src/ServiceProviders/ServiceProvider.php
  src/Views/Form/Templates/Sequoia/assets/css/form.scss
Labels: needs: web doc

#4931 register paypal setting section and add paypal checkout and paypal standard setting to it.
  assets/src/css/admin/settings.scss
  give.php
  includes/admin/class-admin-settings.php
  includes/admin/forms/class-metabox-form-data.php
  includes/admin/settings/class-settings-gateways.php
  includes/class-give-cache-setting.php
  src/PaymentGateways/PayPalCheckout/PayPalCheckout.php
  src/PaymentGateways/PayPalCommerce/AdminSettingFields.php
  src/PaymentGateways/PayPalCommerce/PayPalCommerce.php
  src/PaymentGateways/PayPalStandard/PayPalStandard.php
  src/PaymentGateways/PaymentGateway.php
  src/PaymentGateways/PaypalSettingPage.php
  src/PaymentGateways/SettingPage.php
  src/ServiceProviders/PaymentGateways.php
  src/Views/Admin/UpsellNotice.php
Labels: is: awaiting changes, needs: web doc

#4916 Setup page is now scaffolded
  assets/src/css/admin/setup.scss
  give.php
  includes/admin/settings/class-settings-advanced.php
  includes/install.php
  readme.txt
  src/Onboarding/Onboarding.php
  src/Views/Admin.php
  src/Views/Admin/Pages/Setup.php
  src/Views/Admin/Pages/templates/setup-step-template.php
  src/Views/Admin/Pages/templates/setup-template.php
  webpack.config.js
Labels: needs: testing, needs: web doc

#4951 Onboarding Wizard design is now implemented
  assets/src/js/admin/onboarding-wizard/app/steps/donation-form/index.js
  assets/src/js/admin/onboarding-wizard/app/steps/donation-form/style.scss
  assets/src/js/admin/onboarding-wizard/app/steps/fundraising-needs/index.js
  assets/src/js/admin/onboarding-wizard/app/steps/fundraising-needs/style.scss
  assets/src/js/admin/onboarding-wizard/app/steps/introduction/index.js
  assets/src/js/admin/onboarding-wizard/app/steps/introduction/style.scss
  assets/src/js/admin/onboarding-wizard/app/steps/location/index.js
  assets/src/js/admin/onboarding-wizard/app/steps/location/style.scss
  assets/src/js/admin/onboarding-wizard/app/steps/your-cause/index.js
  assets/src/js/admin/onboarding-wizard/app/steps/your-cause/style.scss
  assets/src/js/admin/onboarding-wizard/components/badge/index.js
  assets/src/js/admin/onboarding-wizard/components/badge/style.scss
  assets/src/js/admin/onboarding-wizard/components/button/style.scss
  assets/src/js/admin/onboarding-wizard/components/card-input/style.scss
  assets/src/js/admin/onboarding-wizard/components/card/style.scss
  assets/src/js/admin/onboarding-wizard/components/continue-button/index.js
  assets/src/js/admin/onboarding-wizard/components/continue-button/style.scss
  assets/src/js/admin/onboarding-wizard/components/donation-form/index.js
  assets/src/js/admin/onboarding-wizard/components/give-logo/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/chevron/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/custom-form-fields/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/dedicate-donations/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/donors-cover-fees/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/gradient-chevron/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/individual/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/multiple-currencies/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/one-time-donation/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/organization/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/other/index.js
  assets/src/js/admin/onboarding-wizard/components/icons/recurring-donations/index.js
  assets/src/js/admin/onboarding-wizard/components/select-input/index.js
  assets/src/js/admin/onboarding-wizard/components/select-input/style.scss
  assets/src/js/admin/onboarding-wizard/components/step-link/index.js
  assets/src/js/admin/onboarding-wizard/components/step-link/style.scss
  src/Onboarding/Wizard/Page.php
Labels: needs: contextual doc
